### ISSUE TITLE
[Elevator] Authorization error

### ISSUE THREAD

**Issue by rvachev** [effectivemade/labs-office-elevator#16]
## Describe the bug
When trying to call an elevator I get `Authorization Error`. The only way to fix it is to logout and login again

## Pre-requirements
You have to be logged in for a few days

## To Reproduce
1. Open an application
2. Press button
3. Get `Authorization error`

## Expected behavior
The elevator is called with no errors

## Priority
P2
[Reference - Google Issue tracker priority levels](https://developers.google.com/issue-tracker/concepts/issues#priority)

## Screenshots/Video
https://user-images.githubusercontent.com/33893991/232507644-ff53154b-56e0-4991-b95f-b9a32bdf60d0.mp4

## Mobile
 - Device: Google Pixel 6 Pro
 - OS: Android 13
 - Version: 1.0.0

**Comment by Radch-enko** [comment]
After much refactoring, the authorization logic has been improved as well. To be sure you need to do some testing. While the office is unavailable I will close the issue and come back to it later.
